//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//

import UIKit

struct ___VARIABLE_productName:identifier___Configurator {

	static func createModule() -> UIViewController {
        var view: ___VARIABLE_productName:identifier___ViewController!

        let viewController = UIStoryboard.init(name: "___VARIABLE_productName:identifier___", bundle: Bundle.main).instantiateInitialViewController()
        if viewController == nil {
            fatalError("Seems there is no initial view controller in ___VARIABLE_productName:identifier___.storyboard")
        }

        if viewController is UINavigationController {
            view = (viewController as! UINavigationController).viewControllers.first as! ___VARIABLE_productName:identifier___ViewController
        } else {
            view = viewController as! ___VARIABLE_productName:identifier___ViewController
        }

        let interactor = ___VARIABLE_productName:identifier___Interactor()
        let router = ___VARIABLE_productName:identifier___Router()
        let presenter = ___VARIABLE_productName:identifier___Presenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return viewController!
    }
}
