//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//

import UIKit

class ___VARIABLE_productName:identifier___ViewController: UIViewController {

	var presenter: ___VARIABLE_productName:identifier___PresenterInterface?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}

// MARK: - ___VARIABLE_productName:identifier___View
extension ___VARIABLE_productName:identifier___ViewController: ___VARIABLE_productName:identifier___View {
    
}
