//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import Foundation

final class ___VARIABLE_moduleName___Interactor: ___VARIABLE_moduleName___InteractorInput {
    
    // MARK: - Properties
    weak var presenter: ___VARIABLE_moduleName___InteractorOutput?
    
    // MARK: - ___VARIABLE_moduleName___InteractorInput
}
