//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//

import UIKit

class ___VARIABLE_productName:identifier___Router {
    // MARK: - Properties
    weak var viewController: UIViewController?
}

// MARK: - ___VARIABLE_productName:identifier___WireframeInterface -
extension ___VARIABLE_productName:identifier___Router: ___VARIABLE_productName:identifier___WireframeInterface {
    
    func navigate(to option: ___VARIABLE_productName:identifier___NavigationOption) {
//        switch option {
//        case .firstModule:
//              openFirstModule()
//        case .secondModule(let someData):
        //      openSecondModule(with someData)
//        }
    }
}
