//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import UIKit

final class ___VARIABLE_moduleName___Router {
    
    // MARK: - Properties
    weak var viewController: UIViewController?
}

// MARK: - ___VARIABLE_moduleName___WireframeInterface
extension ___VARIABLE_moduleName___Router: ___VARIABLE_moduleName___WireframeInterface {
    
    func navigate(to option: ___VARIABLE_moduleName___NavigationOption) {
//        switch option {
//        case .firstModule:
//            openFirstModule()
//        case .secondModule(let someData):
//            openSecondModule(with someData)
//        }
    }
}
