//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import UIKit

final class ___VARIABLE_moduleName___ViewController: UIViewController {
    
    // MARK: - Properties
    var presenter: ___VARIABLE_moduleName___PresenterInterface?
    
    // MARK: - Lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
    }
}

// MARK: - ___VARIABLE_moduleName___View
extension ___VARIABLE_moduleName___ViewController: ___VARIABLE_moduleName___View {
    
}
